### ISSUE TITLE
BFS Algorithm Of Graph 

### ISSUE THREAD

**Issue by rishabhgarg25699** [onbitSyn/algobook#1]
BFS is a traversing algorithm where you should start traversing from a selected node (source or starting node) and traverse the graph layerwise thus exploring the neighbour nodes (nodes which are directly connected to source node). You must then move towards the next-level neighbour nodes.
I want to implement this algorithm.

**Comment by onbit-uchenik** [comment]
Well done @rishabhgarg25699
